application: dartendo
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  login: admin

- url: /
  static_files: nesdart.html
  upload: nesdart.html
  login: admin

- url: /(.*\.(html|css|js|png|json|nes|jpg|gif))
  static_files: \1
  upload: (.*\.(html|css|js|png|json|nes|jpg|gif))
  login: admin

- url: /(.*\.dart)
  static_files: \1
  upload: (.*\.dart)
  login: admin
  mime_type: application/dart

- url: (.*)
  script: main.app
  login: admin

inbound_services:
- channel_presence