application: dartendo
version: 3
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /
  static_files: dartendo.html
  upload: dartendo.html

- url: /(.*\.(html|css|js|png|json|nes|jpg|gif|swf))
  static_files: \1
  upload: (.*\.(html|css|js|png|json|nes|jpg|gif|swf))

- url: /(.*\.dart)
  static_files: \1
  upload: (.*\.dart)
  mime_type: application/dart

- url: (.*)
  script: main.app