application: dartendo
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /
  static_files: nesdart.html
  upload: nesdart.html

- url: /(.*\.(html|css|js|png))
  static_files: \1
  upload: (.*\.(html|css|js|png))

- url: (.*)
  script: main.app